// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package accounts is a generated GoMock package.
package accounts

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// RetrieveAccountByID mocks base method.
func (m *MockRepository) RetrieveAccountByID(ctx context.Context, accountID int64, orgID string) (Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveAccountByID", ctx, accountID, orgID)
	ret0, _ := ret[0].(Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveAccountByID indicates an expected call of RetrieveAccountByID.
func (mr *MockRepositoryMockRecorder) RetrieveAccountByID(ctx, accountID, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveAccountByID", reflect.TypeOf((*MockRepository)(nil).RetrieveAccountByID), ctx, accountID, orgID)
}

// SaveEntryAndUpdateAccount mocks base method.
func (m *MockRepository) SaveEntryAndUpdateAccount(ctx context.Context, e Entry, a Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntryAndUpdateAccount", ctx, e, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntryAndUpdateAccount indicates an expected call of SaveEntryAndUpdateAccount.
func (mr *MockRepositoryMockRecorder) SaveEntryAndUpdateAccount(ctx, e, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntryAndUpdateAccount", reflect.TypeOf((*MockRepository)(nil).SaveEntryAndUpdateAccount), ctx, e, a)
}

// SaveNewAccount mocks base method.
func (m *MockRepository) SaveNewAccount(ctx context.Context, a Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNewAccount", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNewAccount indicates an expected call of SaveNewAccount.
func (mr *MockRepositoryMockRecorder) SaveNewAccount(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNewAccount", reflect.TypeOf((*MockRepository)(nil).SaveNewAccount), ctx, a)
}

// UpdateExistingAccount mocks base method.
func (m *MockRepository) UpdateExistingAccount(ctx context.Context, a Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExistingAccount", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExistingAccount indicates an expected call of UpdateExistingAccount.
func (mr *MockRepositoryMockRecorder) UpdateExistingAccount(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExistingAccount", reflect.TypeOf((*MockRepository)(nil).UpdateExistingAccount), ctx, a)
}
