// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package accounts is a generated GoMock package.
package accounts

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// RetrieveAccountByID mocks base method.
func (m *MockRepository) RetrieveAccountByID(ctx context.Context, accountID int64, orgID string) (Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveAccountByID", ctx, accountID, orgID)
	ret0, _ := ret[0].(Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveAccountByID indicates an expected call of RetrieveAccountByID.
func (mr *MockRepositoryMockRecorder) RetrieveAccountByID(ctx, accountID, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveAccountByID", reflect.TypeOf((*MockRepository)(nil).RetrieveAccountByID), ctx, accountID, orgID)
}

// SaveEntryAndUpdateAccount mocks base method.
func (m *MockRepository) SaveEntryAndUpdateAccount(ctx context.Context, e Entry, a Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntryAndUpdateAccount", ctx, e, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntryAndUpdateAccount indicates an expected call of SaveEntryAndUpdateAccount.
func (mr *MockRepositoryMockRecorder) SaveEntryAndUpdateAccount(ctx, e, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntryAndUpdateAccount", reflect.TypeOf((*MockRepository)(nil).SaveEntryAndUpdateAccount), ctx, e, a)
}

// SaveNewAccount mocks base method.
func (m *MockRepository) SaveNewAccount(ctx context.Context, a Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNewAccount", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNewAccount indicates an expected call of SaveNewAccount.
func (mr *MockRepositoryMockRecorder) SaveNewAccount(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNewAccount", reflect.TypeOf((*MockRepository)(nil).SaveNewAccount), ctx, a)
}

// UpdateExistingAccount mocks base method.
func (m *MockRepository) UpdateExistingAccount(ctx context.Context, a Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExistingAccount", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExistingAccount indicates an expected call of UpdateExistingAccount.
func (mr *MockRepositoryMockRecorder) UpdateExistingAccount(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExistingAccount", reflect.TypeOf((*MockRepository)(nil).UpdateExistingAccount), ctx, a)
}

// MockTopic is a mock of Topic interface.
type MockTopic struct {
	ctrl     *gomock.Controller
	recorder *MockTopicMockRecorder
}

// MockTopicMockRecorder is the mock recorder for MockTopic.
type MockTopicMockRecorder struct {
	mock *MockTopic
}

// NewMockTopic creates a new mock instance.
func NewMockTopic(ctrl *gomock.Controller) *MockTopic {
	mock := &MockTopic{ctrl: ctrl}
	mock.recorder = &MockTopicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopic) EXPECT() *MockTopicMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockTopic) Emit(ctx context.Context, e Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emit", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Emit indicates an expected call of Emit.
func (mr *MockTopicMockRecorder) Emit(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockTopic)(nil).Emit), ctx, e)
}

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// EventData mocks base method.
func (m *MockEvent) EventData() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventData")
	ret0, _ := ret[0].(any)
	return ret0
}

// EventData indicates an expected call of EventData.
func (mr *MockEventMockRecorder) EventData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventData", reflect.TypeOf((*MockEvent)(nil).EventData))
}

// EventType mocks base method.
func (m *MockEvent) EventType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventType")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventType indicates an expected call of EventType.
func (mr *MockEventMockRecorder) EventType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventType", reflect.TypeOf((*MockEvent)(nil).EventType))
}
