apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    com.job.service: mysql-db
    tier: mysql
spec:
  selector: 
    matchLabels:
      com.job.service: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        com.job.service: mysql-db
        tier: mysql
    spec:
      serviceAccountName: default
      containers:
        - name: mysql-db
          image: mysql
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_DATABASE
              value: balances
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: mysql-secrets
                   key: root
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: mysql-secrets
                   key: balances                   
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql 
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim     
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    com.job.service: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    com.job.service: mysql-db
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
  labels:
    com.job.service: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi