@startuml C4 - Diagrama Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/devicons/go.puml

AddRelTag("async", $lineStyle = DashedLine())
SHOW_PERSON_PORTRAIT()

Person_Ext(bancos, "Agentes Financeiros", "Cliente externo que irá consulta as transações realizadas pelo sistema de pagamentos")

System_Boundary(tpsapi, "Sistema de transações de débito e crédito"){
Container(command, "Serviço de Transações", "Golang", "Processa a solicitação enviada, realizando debitos ou creditos na conta informada", $sprite = "go")
ContainerQueue(sns, "Servidor de Mensagens", "SNS", "Dados da transação para ser consumido")
ContainerQueue(sqs, "Fila de Mensagens", "SQS", "Fila dos dados da transação para ser consumido")
ContainerDb(dbWriter, "Banco de dados de escrita", "MySQL", "Armazena os dados das transações requisitadas")
ContainerDb(dbReader, "Banco de dados de leitura", "MySQL", "Armazena os dados da transações processadas")
Container(worker, "Processador de Transações", "Golang", "Processa os dados da transação e disponibiliza para consulta", $sprite = "go")

Rel(bancos, command, "Solicita a abertura de uma conta", "JSON")
Rel(bancos, command, "Solicita uma transação de Debito ou Credito", "JSON")
Rel(sqs, sns, "Consome dados da transação publicados no tópico", "JSON", $tags = "async")
Rel(bancos, worker, "Consulta as transações efetivadas", "JSON")
Rel(worker, sqs, "Consome os dados enfileirados", "JSON", $tags = "async")
Rel(worker, dbReader, "Envia os dados da transação processada", "MySQL")
Rel(command, sns, "Publica dados da transação processada", "JSON", $tags = "async")
Rel(command, dbWriter, "Envia os dados da transação requisitada", "JSON")

}

@enduml